package com.ecotrack.backend.activity;
import com.ecotrack.backend.emission.EmissionFactor; import com.ecotrack.backend.user.User; import jakarta.persistence.*; import java.time.*;
@Entity @Table(name="activities") public class Activity{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) Long id;
 @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="user_id") User user;
 @Column(nullable=false) String category; @Column(nullable=false) String activityType; @Column(nullable=false) double quantity; @Column(nullable=false) String unit; @Column(nullable=false) double emission;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="emission_factor_id") EmissionFactor emissionFactor; String emissionFactorVersion; @Column(nullable=false) LocalDate activityDate; @Column(columnDefinition="json") String metadata; @Column(nullable=false) Instant createdAt=Instant.now();
 public Long getId(){return id;} public User getUser(){return user;} public void setUser(User v){user=v;} public String getCategory(){return category;} public void setCategory(String v){category=v;} public String getActivityType(){return activityType;} public void setActivityType(String v){activityType=v;} public double getQuantity(){return quantity;} public void setQuantity(double v){quantity=v;} public String getUnit(){return unit;} public void setUnit(String v){unit=v;} public double getEmission(){return emission;} public void setEmission(double v){emission=v;} public EmissionFactor getEmissionFactor(){return emissionFactor;} public void setEmissionFactor(EmissionFactor v){emissionFactor=v;} public String getEmissionFactorVersion(){return emissionFactorVersion;} public void setEmissionFactorVersion(String v){emissionFactorVersion=v;} public LocalDate getActivityDate(){return activityDate;} public void setActivityDate(LocalDate v){activityDate=v;} public String getMetadata(){return metadata;} public void setMetadata(String v){metadata=v;} public Instant getCreatedAt(){return createdAt;}
}
