import {
  Sparkles,
  Leaf,
  Car,
  Zap,
  Utensils,
  Recycle,
  Droplets,
  ArrowRight,
  CheckCircle,
  TrendingDown,
} from "lucide-react";

export default function Advisor() {
  const recommendations = [
    {
      icon: <Car size={21} />,
      category: "Transportation",
      title: "Use public transport twice a week",
      description:
        "Transportation is currently your largest emission source. Replacing two car trips every week could significantly reduce your footprint.",
      saving: "28 kg CO₂/month",
      impact: "High Impact",
    },
    {
      icon: <Zap size={21} />,
      category: "Electricity",
      title: "Reduce unnecessary electricity usage",
      description:
        "Turn off unused appliances and consider energy-efficient lighting to reduce your monthly electricity consumption.",
      saving: "12 kg CO₂/month",
      impact: "Medium Impact",
    },
    {
      icon: <Utensils size={21} />,
      category: "Food",
      title: "Choose more plant-based meals",
      description:
        "Replacing a few high-emission meals with plant-based alternatives can reduce your food-related carbon footprint.",
      saving: "10 kg CO₂/month",
      impact: "Medium Impact",
    },
    {
      icon: <Recycle size={21} />,
      category: "Waste",
      title: "Increase household recycling",
      description:
        "Separating recyclable materials from general waste can lower waste-related emissions.",
      saving: "6 kg CO₂/month",
      impact: "Low Impact",
    },
  ];

  return (
    <div className="advisor-page">

      {/* HEADER */}

      <div className="advisor-hero">

        <div className="advisor-sparkle">
          <Sparkles size={27} />
        </div>

        <div>
          <span>AI POWERED</span>

          <h1>
            Sustainability Advisor
          </h1>

          <p>
            Personalized recommendations to help
            you reduce your environmental impact.
          </p>
        </div>

      </div>

      {/* AI SUMMARY */}

      <div className="advisor-summary">

        <div className="advisor-summary-icon">
          <Sparkles size={24} />
        </div>

        <div className="advisor-summary-content">

          <span>
            AI ANALYSIS
          </span>

          <h2>
            Your biggest opportunity is transportation.
          </h2>

          <p>
            Based on your recent activity, transportation
            contributes approximately 43% of your monthly
            carbon footprint. Small changes to your travel
            habits could make a significant difference.
          </p>

        </div>

        <div className="advisor-potential">

          <TrendingDown size={18} />

          <span>
            Potential monthly reduction
          </span>

          <strong>
            56 kg CO₂
          </strong>

        </div>

      </div>

      {/* RECOMMENDATIONS */}

      <div className="advisor-section-header">

        <div>
          <h2>
            Personalized Recommendations
          </h2>

          <p>
            Actions prioritized according to their
            potential environmental impact.
          </p>
        </div>

      </div>

      <div className="recommendations-grid">

        {recommendations.map((item, index) => (

          <div
            className="recommendation-card"
            key={index}
          >

            <div className="recommendation-top">

              <div className="recommendation-icon">
                {item.icon}
              </div>

              <span className="impact-badge">
                {item.impact}
              </span>

            </div>

            <span className="recommendation-category">
              {item.category}
            </span>

            <h3>
              {item.title}
            </h3>

            <p>
              {item.description}
            </p>

            <div className="recommendation-saving">

              <TrendingDown size={15} />

              <strong>
                Potential saving
              </strong>

              <span>
                {item.saving}
              </span>

            </div>

            <button className="recommendation-button">
              Start This Action
              <ArrowRight size={14} />
            </button>

          </div>

        ))}

      </div>

      {/* HOW AI WORKS */}

      <div className="ai-how-section">

        <div className="ai-how-icon">
          <Leaf size={24} />
        </div>

        <div>

          <h2>
            How EcoTrack AI works
          </h2>

          <p>
            Your recommendations will be generated by
            analyzing your transportation, electricity,
            food, waste and water consumption patterns.
          </p>

        </div>

        <div className="ai-process">

          <span>
            <CheckCircle size={14} />
            Analyze
          </span>

          <span>
            <CheckCircle size={14} />
            Identify
          </span>

          <span>
            <CheckCircle size={14} />
            Recommend
          </span>

        </div>

      </div>

    </div>
  );
}